### ISSUE TITLE
Make future passes clear that they're not yet active

### ISSUE THREAD

**Issue by danielrbradley** [o2Labs/office-booker#70]
Currently, it could be misleading that we show them a pass which they can't yet use. It's nice to be able to show them what the pass looks like, but perhaps we need to make it clearer that it's not yet active.

E.g. Could we use the phrase "preview" or use an 'inactive' colour scheme while it's in preview? Also, should any buttons leading to the pass indicate that it's also just a preview.

Perhaps we should also lead the user to understand that the pass should always be presented in the app so the data is live?

**Comment by chapmanio** [comment]
The current screenshot is intentionally set to focus on the date rather than the day of the week, to avoid this issue:

![Screenshot 2020-08-04 at 12 34 33](https://user-images.githubusercontent.com/10833481/89289278-de160680-d64e-11ea-9734-aa7ed3f17db7.png)

As a result, I don't think anything else is required to show if the booking is today or in the future - this is just down to security, etc, being vigilant.
